replicaCount: 1

image:
  repository: fuerst/etherpad-docker
  tag: stable

service:
  type: ClusterIP
  port: 9001

ingress:
  enabled: true
  hosts:
    - etherpad.teamhephy.info

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 2Gi
  existingClaim: ""
  storageClassName: ""
